services:
  https-portal:
    image: steveltn/https-portal
    container_name: https-portal
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: 'kivi.pivotfox.de -> http://kivi:80'
      STAGE: 'production'
    volumes:
      - ./certs:/etc/nginx/certs
    networks:
      - kivinet
    restart: unless-stopped

  kivi:
    build:
      context: ./kivitendo-docker
      args:
        - BUILD_DATE=${BDATE}
        - VERSION=${VERSION}
        - LOCALE=${LOCALE}
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - KIVITENDO_TEMPLATE=${KIVITENDO_TEMPLATE}
    image: pfoxkivi:latest
    container_name: ${NAME_KIVI}
    environment:
      - postgres_host
      - postgres_user
      - postgres_password
      - kivitendo_version
      - kivitendo_user
      - kivitendo_password
      - kivitendo_adminpassword
      - CRM
      - cups_user
      - cups_password
      - root_alias
      - kivitendo_crm_version
      - kivitendo_crm_branch
    volumes:
      - kivid_config:/var/www/kivitendo-erp/config
      - kivid_templ:/var/www/kivitendo-erp/templates/company
      - kivid_webdav:/var/www/kivitendo-erp/webdav
      - kivid_documents:/var/www/kivitendo-erp/kivi_documents
      - kivid_patches:/var/www/patches
      - kivid_cups:/etc/cups
      - kivid_exim:/etc/exim4
      - /var/run/dbus:/var/run/dbus
    networks:
      - kivinet
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: ${NAME_DB}
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_USER=${postgres_user}
      - PGDATA
      #- POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:${PGDATA}
    networks:
      - kivinet
    restart: unless-stopped

networks:
  kivinet:
    driver: bridge

volumes:
  postgres:
  kivid_templ:
  kivid_config:
  kivid_webdav:
  kivid_documents:
  kivid_patches:
  kivid_cups:
  kivid_exim:
